name: CI-CD
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.10.0
      - name: Autenticando o usuário no Docker
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.USER}}
          password: ${{secrets.PASS}}
      - name: Buildando e envinado para o DOckerHub
        uses: docker/build-push-action@v6.16.0
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            giancarloh/manga-app-api:latest
            giancarloh/manga-app-api:${{github.run_number}}
